### ISSUE TITLE
Ruin entrance is blocked when entering surface that way

### ISSUE THREAD

**Issue by bailli** [thezerothcat/LaMulanaRandomizer#100]
Hey,
I did a run with randomized starting position the other day. I found the surface first through a normal screen transition to the ruin entrance. But since the entrance was still blocked (because I did not approach it "the normal way") I clipped into the wall and was sent back to my starting position (GoT Surface).

Is this intended? The seed was winable since I could enter the surface after beating Bahamut.

Thanks for your work on the randomizer. I am looking forward to randomized enemies :)

**Comment by thezerothcat** [comment]
If you jump, there should be a warp taking you back to the transition you came from. If that didn't work, then there's probably a bug.

Looking at the code, I think I see what might've gone wrong - do you happen to remember where the ruin entrance led, or have the settings string from the playthrough?

If not, that's fine - I realize this is a bit of a delayed reply, and even if I can't verify your problem specifically, I can at least check the problem I think exists and make sure that works as intended.

I'll also update documentation to mention that you aren't actually meant to reach the surface from that transition.

Thank you for letting me know about this, and apologies for the bug.

**Comment by bailli** [comment]
The ruin entrance led to the Tower of the Goddess - the one almost at the bottom. (I think the randomizer calls it Urd's Tower.)

Well if it is itended to only reach the surface by backside door or Bahamut, then this is a very small bug ;)
