### ISSUE TITLE
Additional Details For Unusual Interactions Wiki Page

### ISSUE THREAD

**Issue by jcbantuelle** [thezerothcat/LaMulanaRandomizer#102]
First of all, thank you so much for creating this Randomizer. I adore it so much and have loved having a way to breathe new life and experiences into my favorite game.

Regarding the issue report, in the Unusual Interactions wiki page section https://github.com/thezerothcat/LaMulanaRandomizer/wiki/Unusual-Interactions#tower-of-the-goddess-without-bronze-mirror it mentions that you may need to access the Tower via Gate of Time, however it doesn't mention that there's a breakable wall that will enable you to access the rest of the tower even if you can't jump out of the pipes with the feather.

I got stumped and ended up asking for help on the Discord server because I wasn't aware of this breakable wall, so figured I'd mention it in case you were interested in adding it to the wiki to help future players who might get stuck like me.

I'd open a PR for it but I don't think github permits those on Wikis. If it helps, here's a possible draft:

"You may be expected to use Gate of Time to access Tower of the Goddess for the first time. If so, there's a breakable wall above the pipes on the right-hand side that allows access to the remainder of the tower."

**Comment by thezerothcat** [comment]
Thanks! I've added it with a slight adjustment to mention the lack of Feather, since you can just jump out of the pipes if you have it.
