### ISSUE TITLE
Rando licensing update

### ISSUE THREAD

**Issue by thezerothcat** [thezerothcat/LaMulanaRandomizer#112]
It's been brought up that the randomizer lacks a license statement. I'd like to use this one: https://opensource.org/licenses/BSD-2-Clause

To existing contributors, please indicate if you are okay with this change, and if your contributions are enough that you'd like to be included on the copyright statement, please indicate your preferred name so I can put it on there.

Thanks!

**Comment by thezerothcat** [comment]
- [ ] Approval by @Goost91 
- [ ] Approval by @halgorithm 
- [ ] Approval by @tkoehlmann 
- [ ] Approval by @jcbantuelle 
- [ ] Approval by @N-eil 
- [ ] Approval by @smurfton 
- [ ] Approval by @worsety 
- [ ] Approval by @thezerothcat

**Comment by thezerothcat** [comment]
Will be included on copyright as thezerothcat

**Comment by worsety** [comment]
'k

**Comment by halgorithm** [comment]
I approve

**Comment by Goost91** [comment]
All fine by me

**Comment by jcbantuelle** [comment]
I approve and have no desire to be included on the copyright

**Comment by tkoehlmann** [comment]
The license is okay. I believe my only contribution was the Linux compatibility. So please use the Github nickname and redirect such bug reports to me.

**Comment by thezerothcat** [comment]
I've committed a license file to the master branch. Most people didn't specify a preference regarding copyright mentions, so most people are just included under "portions copyright other contributors." If I missed any direct mentions, please let me know or make a pull request, and I'll get the license updated. Thanks everyone!
