### ISSUE TITLE
You cannot select Boss Specific Ankh Jewels, or Blocks need gloves to push, from the GUI

### ISSUE THREAD

**Issue by f-raZ0R** [thezerothcat/LaMulanaRandomizer#115]
In the code, those options exist, however, you can't select them in the GUI right now.

**Comment by thezerothcat** [comment]
Very late response due to some time away from the randomizer, but the reason for this is that those features were never finished.

**Comment by f-raZ0R** [comment]
Will either feature ever see the light of day?
