### ISSUE TITLE
requireSoftwareComboForKeyFairy not respected

### ISSUE THREAD

**Issue by dou8le88** [thezerothcat/LaMulanaRandomizer#119]
This one is a bit of a doozy here, and I'm not sure if it's really this setting that's broken or if the game thinks there's access to the Gate of Illusion shop when there's not. I could also be wrong about shop access but I'm not aware of any way to get to the shop without the Anchor to complete the lower Gate of Illusion puzzles, at least with damage boosting disabled.

So to beat the game, we need the Vessel in the Gate of Illusion shop. To get there, we need the Anchor, which is in the Shrine of the Mother in the Crystal Skull chest. To get there, we need to place the Dragon Bone. The Dragon Bone is where emusic.exe is normally located, the bombable scannable ice wall in Graveyard of the Giants. To get that, we need torude.exe to scan the wall. Torude.exe is in the Gate of Time, so we need a key fairy to get it.

Mekuri.exe, to guarantee a key fairy, is located where the Death Seal is in vanilla, in the Shrine of the Mother access from the philosopher-locked Endless Corridor 2F ladder. But wait, that room requires the Dragon Bone be placed to get the chest. So we need the Dragon Bone to get mekuri.exe, but to get the Dragon Bone we need to visit the Gate of Time which is locked by a key fairy.
[doors.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296236/doors.txt)
[gates.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296237/gates.txt)
[items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296238/items.txt)
[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296266/randomizer-config.txt)
[removed_items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296240/removed_items.txt)
[shops.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/5296241/shops.txt)

**Comment by Wymar** [comment]
Have you tried skipping the anchor by diving into the water with caltrops?

**Comment by dou8le88** [comment]
Yeah in my rando config you can see I have
```
dboost.Enemy=false
dboost.Item=false
dboost.Environment=false
```

**Comment by rainbowtrout07** [comment]
If you beat all 8 bosses, and the shrine of the mother activates, the mekuri location no longer requires the dragon bone, which should put everything in logic.  So I don't think there's any problem here.

**Comment by dou8le88** [comment]
Oh, that's an interesting interaction. Good to know.
