### ISSUE TITLE
Wrong requirements for Chamber of Extinction access

### ISSUE THREAD

**Issue by ExoSDA** [thezerothcat/LaMulanaRandomizer#12]
"Chamber of Extinction [Main] => Location: Shrine of the Mother [Main]"

also requires feather to make it past the grailpoint hill or  being able to remove skull walls in shrine of the mother (shrine map+dragon bone+yagomap+yagostr)

**Comment by thezerothcat** [comment]
Chamber of Extinction requirements updated to:
Chamber of Extinction [Main] => Origin Seal
Chamber of Extinction [Main] => Location: Shrine of the Mother [Main], Feather
Chamber of Extinction [Main] => Location: Shrine of the Mother [Main], Map (Shrine of the Mother), yagomap.exe, yagostr.exe, Dragon Bone
