### ISSUE TITLE
Earth Spear can require the Earth Spear to obtain

### ISSUE THREAD

**Issue by GauRocks** [thezerothcat/LaMulanaRandomizer#14]
The Earth Spear can be in chests that require the Earth Spear to open.  For example, in seed 917085441, it appears in the Magatama Jewel chest.  The Magatama Jewel chest requires the Mulana Talisman, which requires the Diary, which requires the Talisman, which requires beating Viy.  Reaching Viy without glitches requires the Earth Spear.

EDIT: This seed caused the issue in version 1.0.9, which was the newest when this was posted.

**Comment by ketsuzoku** [comment]
This is because the Talisman isn't listed as a requirement for getting the Diary.

Diary => Location: Shrine of the Mother [Main], yagomap.exe, yagostr.exe, Map (Shrine of the Mother), Dragon Bone

**Comment by thezerothcat** [comment]
It's been added, thanks!
