### ISSUE TITLE
Crucifix Chest Bug

### ISSUE THREAD

**Issue by Sephalos** [thezerothcat/LaMulanaRandomizer#25]
I got the Crucifix early on in the game, when I got Life Seal + Flare Gun I went to check the chest and the torches were already lit up with the chest remaining closed.

**Comment by thezerothcat** [comment]
Was this on 1.7? I added a fix for it recently, which I thought I'd included in 1.7. There's an existing/closed issue for it already. If you're still seeing in on newer versions, please let me know.

**Comment by Sephalos** [comment]
I think that was on an older version, 1.6.1? If it's fixed then I guess you should close this issue, sorry for the duplicate. I'll make sure I have the latest version.

**Comment by thezerothcat** [comment]
Not a problem! There's always the risk that I've made a mistake, or that there's something different between versions, so I'd rather hear about the issue than not.
