### ISSUE TITLE
Helmet & Origin Seal Logic

### ISSUE THREAD

**Issue by Sephalos** [thezerothcat/LaMulanaRandomizer#26]
The Helmet was placed in stead of the Flail Whip. To get Tower of the Goddess to appear I would need to defeat Vyi which requires Bahamut to be defeated in order to open the door in the Tower of Ruins. I don't think it's possible to get all the way up to him without the Helmet. 

I currently have the Plane Model but it doesn't allow me to access Tower of the Goddess through alternate entrances (Graveyard of Giants).

**Comment by Sephalos** [comment]
Same applies to Origin Seal. This seed I just did had the Origin Seal replace Plane Model and you need this seal to unlock the Bahamut fight.

**Comment by thezerothcat** [comment]
If you have access to Chamber of Extinction, Isis' Pendant, and a weapon that can hit floors below you, you can enter Tower of the Goddess through Gate of Time. If you lack Origin Seal but have Key of Eternity, Hand Scanner, and reader.exe, you can get to Chamber of Extinction through Shrine of the Mother.

If you have none of those, something may be wrong with requirements. I know there were some requirement bugs around flooding Tower of the Goddess in previous versions, but I believe I've fixed them all by now.

**Comment by thezerothcat** [comment]
Correction: This is broken, but it has nothing to do with Bahamut. You can't open the chest without spawning the platform enemies, and that requires flooding Tower of the Goddess which requires Origin Seal. I left off the flooded tower requirement, and will fix in 1.8.

Thank you for bringing this one to my attention!

**Comment by Sephalos** [comment]
I completely forgot about Gate of Time, I'll keep that area in mind for future runs.
