### ISSUE TITLE
Ancient Software display didn't show obtained item

### ISSUE THREAD

**Issue by TrueHitoare** [thezerothcat/LaMulanaRandomizer#30]
The specific instance was emusic.exe => Ankh Jewel (Chamber of Birth). After using Snapshots to scan the room, I received a notification of "Obtained " with no item displayed. The actual Ankh Jewel was received (fortunately). I already had at least one Ankh Jewel at the time, but happened to notice that the count increased.

**Version:** 1.8.2
**Seed:** 1430114019
**Item Settings:**
Original Positions - Holy Grail, Hand Scanner, reader.exe
Random - All others
**Advanced Settings:**
Off - Allow damage-boosting requirements
On - All others
**Shop Randomization:** Unique items only
**Glitch settings:** All off
**Boss Difficulty:** Lower

**Comment by thezerothcat** [comment]
Not ignoring this one, just need to confirm what's actually happening here. I'll probably place some ankh jewels in specific locations for my next test playthrough - I think this may be related to an issue I already resolved with maps.

**Comment by thezerothcat** [comment]
Ankh jewels can no longer replace the torude scan items. I fixed it a while back but forgot to close the issue - sorry for not updating it sooner!
