### ISSUE TITLE
Item in Knife location did not spawn

### ISSUE THREAD

**Issue by spinachislove** [thezerothcat/LaMulanaRandomizer#42]
After destroying the pot and activating the floor switch, the weapon chest disappears revealing nothing whatsoever. According to the spoiler, there should be an upgraded laptop there. This is on the GOG version of the game and 1.15.0 of the randomizer. The seed is 53818926.
[53818926.zip](https://github.com/thezerothcat/LaMulanaRandomizer/files/1364667/53818926.zip)
If anyone wants to verify this, load the 4th save from the attached files.

**Comment by TrueHitoare** [comment]
This sounds like a recurrence of issue #29 .

**Comment by thezerothcat** [comment]
If you purchased the MSX2 item from the version of the MSX2 shop that didn't have a Sacred Orb, a bug that's been fixed in 1.16.3 would have made the game think you'd picked up the MSX2 already. It should be fixed now.
