### ISSUE TITLE
Not initially accessible?

### ISSUE THREAD

**Issue by dansidney** [thezerothcat/LaMulanaRandomizer#44]
I set the game to have initially accessible Hermes Boots, but I found them by the NPC which normally gives you Mekuri.exe . Am I missing a strategy that you can get there early? I know you need either Hermes boots to be able to steer quickly enough after a jump, or the Feather to double jump there.

(I'm also not sure if it's a bug Xelpud gave me early TextTrack despite me not having selected so, if it's a coincidence it was one heck of it).

Seed 980826842
Randomizer version 1.18
Steam version of the game

**Comment by thezerothcat** [comment]
Mekuri is initially accessible, although the birds and low hp make it a bit challenging.

Safe strats:
Kill the bird while on the upper ladder (so it can't knock you off), move as close as you can to the edge of the platform, jump off the edge and start holding left as soon as you're low enough to not land back on the ledge (err on the side of too early so you'll land back on the platform if you miss). If you bump against the side of the ledge while holding left, you've done it right and will land where the tent is.

I'll look into the TextTrax thing - it could very well be a coincidence, but it doesn't hurt to double check. If it was the original 1.18 release, it was very likely a bug - I ended up deleting it shortly after release and replacing it the next day (I thought I could catch it before anyone got their hands on the bad build, but I really should've just created 1.18.1 instead).

**Comment by dansidney** [comment]
No it's set to RANDOM in the file itself, so this is just a big coincidence I suppose.

I can access the area with Mekuri normally and I've made a few attempts to reach it with a steering jump, and I couldn't. I assumed you needed the boots to get there, but I guess I'll practice it some more.
