### ISSUE TITLE
Temple of the Sun / Temple of Moonlight / Inferno Cavern considered initially accessible (without Holy Grail)?

### ISSUE THREAD

**Issue by oneup40** [thezerothcat/LaMulanaRandomizer#54]
First of all, great work so far. Every year that goes by without a La-Mulana 2 release has made me sad that there's no new La-Mulana to play, but now that I've discovered this randomizer it gives me something to pass the time until then.

Before playing the randomizer recently I hadn't played La-Mulana in a while so I might be overlooking something, but should areas past Temple of the Sun be considered initially accessible? I don't think there's any way out without the Holy Grail and with no other items right? The entrance from Spring in the Sky is one-way, the Gate of Guidance exit can't be reached again without Hermes Boots, the Chamber of Extinction exits require the first seal, and the Twin Labyrinths exit requires defeating Ellmac (which requires an Ankh Jewel of course as well as Hermes Boots or Holy Grail to unlock the minecart to activate the Ankh).

That leaves the Temple of Moonlight and Inferno Cavern exits. Starting with Temple of Moonlight, you can reach Eden but can't make it to the rest of Gate of Illusion without the Fruit. Other than that the only other exit is Twin Labyrinths -- you can't drop down into the rest of Temple of Moonlight without unlocking the room next to the Axe from below.

Inferno Cavern can also make it to Twin Labyrinths, but all the other exits require defeating guardians.

So that leaves Twin Labyrinths as the only possible way back to the rest of the ruins. I have to confess ignorance about Twin Labyrinths before the poison is lifted, but I don't think you can make it back to the area of Twin Labyrinths that connects to Mausoleum of the Giants?

So if you ever enter Temple of the Sun (from either Gate of Guidance or from Spring in the Sky) without the Holy Grail, I think you're stuck in Temple of the Sun / Temple of Moonlight / Inferno Cavern / Twin Labyrinths.

**Comment by TrueHitoare** [comment]
### Temple of the Sun

You can get back to the Guidance Gate exit from any room in Temple of the Sun - except, as far as I can tell, the boss room (I forget where climbing the ladder out of Twin Labyrinths drops you before you lift the poison), but there are no items in or beyond the boss room. From D-5 (the room above the boss room), simply climb up the ladder on the left side of the screen, and you'll be able to get all the way back to the top, no Hermes Boots required. If you're on the right side of the pyramid, there's a one-way door that lets you get inside. Pressing the floor switch in the upper-left part of the pyramid opens an exit at the bottom. The only way you can't get out is if you fall into the trap for the map chest, which...well, you fell for a trap, survival is not guaranteed.

### Temple of Moonlight / Twin Labyrinths / Inferno Cavern

Taking the pyramid warp from Temple of the Sun allows you to reach the upper portion of the Temple of Moonlight. As you mentioned, this section has an exit to the Twin Labyrinths, coming out in room I-5 (lower-right) - again, it's possible to lock yourself out from this exit, but that would be your fault for failing a rather basic trap. From there, you can traverse the bottom row of rooms to the left to reach the B-5, which has an exit to the map room of Inferno Cavern, leading back to the Temple of the Sun. Some puzzle solving in this area allows you to reach the Guidance Gate exit.

**Comment by oneup40** [comment]
TIL that you can break a block to remove the wall that comes down in the room with the Gate of Guidance exit. You're right, once that wall is removed, you can make it there from either side of Temple of the Sun and make it out through there. And use Temple of Moonlight -> Twin Labyrinths -> Inferno Cavern -> Temple of the Sun to get out from Temple of Moonlight.

As far as traps go, those aren't really softlocks because you can reset to your last save. The reason I was concerned about a softlock was because I was thinking if you saved in Temple of the Sun you could never make it back out without the Grail, potentially softlocking if the Grail was in Spring in the Sky or something.

Good stuff.
