### ISSUE TITLE
hitting "apply" in gui doesn't seem to do anything

### ISSUE THREAD

**Issue by ellisonch** [thezerothcat/LaMulanaRandomizer#55]
New user here.  I 
1. ran the randomizer (randomizer-1.20.0.jar)
2. entered my La Mulana install directory (D:\games\steam\steamapps\common\La-Mulana) into the text field
3. otherwise left default settings
4. hit "apply" button

and nothing happens.  No popup, error, message, nothing.  I'm assuming that if it worked, I'd get some kind of message like "Success, go play your game now!" or if it failed, "Something went wrong!"  When I start a new game, Xelpud gives me the mailer.

I'm using:
- JRE 9.0.4
- La Mulana on Steam (1.6.6.2)
- Windows 10 x64

Let me know if there's any more info you need.  I'm not sure what else to offer since there isn't any sort of error message.

**Comment by thezerothcat** [comment]
Caused by using Java 9 instead of 8. I'll be updating the README and wiki to indicate the Java 8 requirement until/unless this gets updated to work with 9.
