### ISSUE TITLE
Item randomization bug in version 1.43.1 (and likely later)

### ISSUE THREAD

**Issue by tkoehlmann** [thezerothcat/LaMulanaRandomizer#63]
I might have found an item randomization bug in 1.43.1 which, from skimming through the commits, is probably not fixed in 1.44 either. I've checked with Mqpg and Kitty but they couldn't figure it out either, so I'm rather confident that it's actually a bug.

The important settings are:

    seed=237271930
    requireSoftwareComboForKeyFairy=true
    requireFullAccess=true
    requireIceCapeForLava=true
    randomizeBacksideDoors=false
    ushumgalluAssist=false

tl;dr: all items allowing me to access ToG is locked behind ToG access

The issue is that I cannot get into the Tower of the Goddess. I would either need to defeat Viy for the back door to open or make my way through the Gate of Time. To defeat Viy I need to make the Ankh appear which requires the Ice Cape (which I don't have). To get through the Gate of Time I'd need to open the door with a key fairy which requires miracle.exe and mekuri.exe (I don't have the latter).

As you can see in the attached files, the Ice Cape is *in* the Tower of the Goddess, so that is not an option. mekuri.exe is located in the chest above Ushumgallu, so I'd have to use his water pillar when fighting him. But I don't have the Dimensional Key either - without that he just won't appear. The Dimensional Key is located at the Cog of the Soul location, which requires Tower of the Goddess access as well.

So it seems the randomizer created a deadlock here.

Attached files:

- [randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2590959/randomizer-config.txt)
- [items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2590961/items.txt)
- [doors.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2590962/doors.txt)
- [removed_items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2590963/removed_items.txt)
- [shops.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2590964/shops.txt)

**Comment by thezerothcat** [comment]
I've reproduced this on 1.44 by manually placing the items in the relevant locations. I'll track down the problem and release a fix soon. Thanks!

**Comment by thezerothcat** [comment]
Found the bug:
```
if(Settings.isRequireIceCapeForLava()) {
    startingNodes.add("Setting: Lava HP");
}
```

Basically the "Require Ice Cape for swimming through lava" setting is doing the opposite of intended in 1.43-1.44. It was likely introduced with subweapon-only changes when I updated the logic for things you have access to at the start.
