### ISSUE TITLE
Ver 2.9.0 Softlock and unobtainable items

### ISSUE THREAD

**Issue by AxelRyman** [thezerothcat/LaMulanaRandomizer#76]
2 different seeds for 2 different problems. 1st is by player mistake, the other from the rando.

911703392 - Door + Gate Randomizer
After entering the Temple of Moonlight from the Temple of the Sun, the Eden/Gate of Illusion exit was changed to the left entrance of Gate of Illusion(The one that leads to Graveyard of thee Giants). The Twin Labyrinth exit lead to Twin Labyrinth's left side(The one 2 screens below Zu). The other exit in Poseidon's room(The one below Peryton) leads to Tower of the Goddess, but with no Plane Model available, you're stuck on top of the statue.

To probably make it easier to understand,
Temple of the Sun Pyramid -> Temple of Moonlight
Temple of Moonlight (Stairway of Eden) <==========> Gate of Illusion (Fool's Confusion Corridor)
Temple of Moonlight (Neptune's Feet) <==========> Twin Labyrinths (Idigna's Room)
Twin Labyrinths (Poseidon's Room) <==========> Tower of the Goddess (Verdandi's Tower)

No Grail was available at this point. Fruit of Eden was available in a shop on the surface, and the entrance to Eden was available as well early on. However if you don't buy it/access Gate of Illusion, and save at one of the 2 save points(Moonlight or Twin Labyrinth), you'd be stuck there and have to restart the seed. Unless you raindrop out. Glitch logic was not on though.

[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2806027/randomizer-config.txt)
[gates.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2806028/gates.txt)

2082532929 - Cog of Soul requires Magatama Jewel, and Magatama Jewel requires Cog of the Soul
Although the seed was still beatable, I'm sure that not being able to access some items wasn't intended. For this one, Cog of Soul was in Mantra.exe's location(The mural in Chamber of Extinction), which requires defeating Horse-face and Ox-head, and use the Magatama Jewel to access. Magatama Jewel however was in the Perfume location in Chamber of Birth...which needs Cog of Soul to activate the Mudmen.

[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2806029/randomizer-config.txt)
[items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2806030/items.txt)

**Comment by thezerothcat** [comment]
After a bit more digging, it looks like "Require all items to be accessible" was disabled by your removal of Spaulder due to a bug in the code. This will be fixed for the next release.
