### ISSUE TITLE
Ver 2.11.1 Unwinnable seed (Shrine of the Mother map at Death Seal location)

### ISSUE THREAD

**Issue by Arrtex** [thezerothcat/LaMulanaRandomizer#78]
I've killed all eight guardians and have almost all items in the game but can't win because I can't finish learning to read the older text. I need to read the tablet next to the death seal chest but I can't get into the room because the skull walls are in the way. I can't solve the dragon skull statue puzzle to remove them because I don't have the map for the shrine of the mother. That map just happens to be in the death seal chest, making it impossible to reach the map or to read that translation tablet.

My config is very similar to the default. My only change was enabling "Randomize cursed chests".
[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2826376/randomizer-config.txt)
[items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2826377/items.txt)

**Comment by thezerothcat** [comment]
The skull walls are in the way after all guardians are defeated? At that point, it should be True Shrine and the skulls blocking the Death Seal chest should be gone.

If the ladder still leads to the original version of Shrine after all bosses are dead, it's a bug and will need to be fixed.

**Comment by Arrtex** [comment]
Yeah, the ladder still leads to the original version of the shrine. I did use one of the back side doors in the true shrine just to see what would happen; I'm not sure if that would be relevant to the bug.

**Comment by thezerothcat** [comment]
It seems I introduced a bug for non-random transitions with the entrance rando changes. I've restored the old code for this case and confirmed that True Shrine is reachable in 2.12.0.

Since the only logic changes in 2.12.0 were related to removed Spaulder, you can probably recreate your seed against the newer version safely and just load your existing save to finish.

**Comment by Arrtex** [comment]
Thank you! It's working fine now.
