### ISSUE TITLE
Helmet not placed (version 2.11)

### ISSUE THREAD

**Issue by goldencow2** [thezerothcat/LaMulanaRandomizer#80]
Seed #1606492285
If the helmet exists, it isn't in the log.
[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2836621/randomizer-config.txt)
[items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2836622/items.txt)

**Comment by dansidney** [comment]
Did you check shops? You didn't include that file. Your settings state shops too are randomized.

**Comment by goldencow2** [comment]
Ha ha, it was hidden under Notepad's textbox for the search function. Effin Notepad.
